pword = "7890"
pword1 = "rs"

m = peripheral.wrap("top")
s = peripheral.find("speaker")
m.setTextScale(2)

m.clear()
m.setCursorPos(2, 6)
m.setTextColor(colors.red)
m.write("    By NII Novopolesie")
sleep(1)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 / ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 - ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 \ ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 / ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 - ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 \ ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 / ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 - ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 \ ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 / ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 - ")
sleep(0.3)
m.clear()
m.setCursorPos(2, 6)
m.write("    BSystem ver. 1.2 \ ")
sleep(0.3)
m.clear()
s.playNote("guitar" , 3.0 , 24)
sleep(0.1)
s.playNote("guitar" , 3.0 , 24)

m.clear()
term.clear()
sleep(1)
m.setTextColor(colors.red)
m.setCursorPos(2, 6)
term.setTextColor(colors.red)
print("Please wait...")
sleep(1)
m.clear()

m.setTextColor(colors.red)
m.setCursorPos(2, 6)
m.write(" Calibrating monitor...")
sleep(1)
m.clear()

m.setTextColor(colors.red)
m.setCursorPos(2, 6)
m.write("       Complete!")
s.playNote("guitar" , 3.0 , 24)
sleep(0.1)
sleep(1)
m.clear()

m.setTextColor(colors.red)
m.setBackgroundColor(colors.black)
m.setTextScale(2)
m.setCursorPos(2, 5)
m.clear()
m.write(" Welcome to the BSystem")
print("Welcome to the BSystem")
sleep(3)
m.setCursorPos(2, 7)
m.write(" Enter the password:")

while true do
function p()
m.setTextScale(2)
m.setCursorPos(2, 5)
m.write("  Welcome to the BSystem")
print("Welcome to the BSystem 1.2")
sleep(1)
m.setCursorPos(2, 7)
m.write("   Enter the password:")
term.clear()
end

term.clear()
term.setCursorPos(1, 1)



write("password: ")
input = read("*")
local core = "end"
 
if input == pword1 then
  m.clear()
  m.setCursorPos(2, 7)
  m.write("Restart the system...")
  sleep(1)
  m.setCursorPos(2, 7)
  s.playNote("guitar" , 3.0 , 8)
  sleep(0.4)
  s.playNote("guitar" , 3.0 , 6)
  m.clear()
  m.write("Goodbye!")
  os.reboot()
end 

if input == pword then
  m.clear()
rs.setOutput("back", true)
  m.setCursorPos(2, 4)
   sleep(1)         
m.setCursorPos(2, 6)
s.playNote("guitar" , 3.0 , 8)
sleep(0.4)
s.playNote("guitar" , 3.0 , 6)
sleep(0.4)
s.playNote("guitar" , 3.0 , 12)

  m.write("         Start!")
sleep(0.9)
s.playNote("guitar" , 3.0 , 8)
sleep(0.4)
s.playNote("guitar" , 3.0 , 6)
sleep(0.4)
s.playNote("guitar" , 3.0 , 12)

   sleep(2)
rs.setOutput("back", false)
sleep(1)
   sleep(1)
  m.clear()
term.clear()
p()
   end
end